version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "Before running tests"
      - pwd
      - ls
      - python --version
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running all unit tests"
      - python3 manage.py test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/var/cache/apt/archives/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/etc/apt/sources.list.d/mysql.list'
    - '/etc/apt/sources.list'